2022-03-26 21:46:00,884 DEBUG utils_log_decorator.py Функция arg_parser вызвана из функции main модуля C:\projects\messenger-app\messenger\server.py
2022-03-26 21:46:00,886 INFO server.py Сервер в работе, порт для подключений 7777, адрес, с которого принимаются подключения , если адрес не указан, принимаются соединения с любых адресов.
2022-03-26 21:46:59,791 DEBUG utils_log_decorator.py Функция arg_parser вызвана из функции main модуля C:\projects\messenger-app\messenger\server.py
2022-03-26 21:46:59,791 INFO server.py Сервер в работе, порт для подключений 7777, адрес, с которого принимаются подключения , если адрес не указан, принимаются соединения с любых адресов.
2022-03-26 21:47:21,393 INFO server.py Установлено соединение с ('127.0.0.1', 54203)
2022-03-26 21:47:21,394 DEBUG utils_log_decorator.py Функция get_message вызвана из функции main модуля C:\projects\messenger-app\messenger\server.py
2022-03-26 21:47:21,394 DEBUG server.py Разбор сообщения от клиента: {'action': 'presence', 'time': 1648306041.392843, 'user': {'account_name': 'test'}}
2022-03-26 21:47:21,396 INFO server.py Клиент ('127.0.0.1', 54203) отключился от сервера
2022-03-26 21:48:57,668 DEBUG utils_log_decorator.py Функция arg_parser вызвана из функции main модуля C:\projects\messenger-app\messenger\server.py
2022-03-26 21:48:57,669 INFO server.py Сервер в работе, порт для подключений 7777, адрес, с которого принимаются подключения , если адрес не указан, принимаются соединения с любых адресов.
2022-03-26 21:48:57,671 INFO server.py Установлено соединение с ('127.0.0.1', 54307)
2022-03-26 21:48:58,183 INFO server.py Установлено соединение с ('127.0.0.1', 54306)
2022-03-26 21:48:58,184 DEBUG utils_log_decorator.py Функция get_message вызвана из функции main модуля C:\projects\messenger-app\messenger\server.py
2022-03-26 21:48:58,184 DEBUG server.py Разбор сообщения от клиента: {'action': 'presence', 'time': 1648306137.6712048, 'user': {'account_name': 'test_client_1'}}
2022-03-26 21:48:58,184 INFO server.py Клиент ('127.0.0.1', 54307) отключился от сервера
2022-03-26 21:48:59,191 DEBUG utils_log_decorator.py Функция get_message вызвана из функции main модуля C:\projects\messenger-app\messenger\server.py
2022-03-26 21:48:59,193 DEBUG server.py Разбор сообщения от клиента: {'action': 'presence', 'time': 1648306138.1833935, 'user': {'account_name': 'test_client_2'}}
2022-03-26 21:48:59,195 INFO server.py Клиент ('127.0.0.1', 54306) отключился от сервера
